import type { Metadata } from "next";
import RootElements from "./_components/RootElements";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootElements>{children}</RootElements>;
}
